### ISSUE TITLE
Features: Torrent sites and AniDB

### ISSUE THREAD

**Issue by Ianunaut** [GhostWriterTNCS/OtakuManager#1]
If you manage to make this work with Torrent sites (Nyaa, TT, AniDex) and hook it up to the AniDB database, I'm sold. Streaming sites have awful quality.

**Comment by GhostWriterTNCS** [comment]
Ok, I'll work on it. Otaku Manager is not a downloader (at least for now), but I'm glad to make it work with any anime site.
Of course, if you want, you can contribute adding some of this sites (today I'll start to work on Nyaa).
Thank you for your feedback ^.^

**Comment by Natsu6767** [comment]
I would like to help make Otaku Manager work with 9Anime. How should I begin?

**Comment by GhostWriterTNCS** [comment]
Hi! You can fork the project, then take a look to this small guide https://github.com/GhostWriterTNCS/OtakuManager/blob/master/How%20to%20add%20a%20website.md
I've just pushed a new commit to make easier to add a new website.
If you have more questions, feel free to ask ^.^
